# Generated by Django 2.1.5 on 2019-01-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_pay', models.FloatField()),
                ('commission_rate', models.CharField(max_length=100)),
                ('task_quantity', models.IntegerField()),
                ('superior_income_rate', models.CharField(max_length=100)),
                ('shop_manager', models.BooleanField(default=False)),
                ('on_job', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='wage.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Monthlymoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('base_salary', models.FloatField(default=0)),
                ('commission_current', models.FloatField(default=0)),
                ('commission_before', models.FloatField(default=0)),
                ('commission_passive', models.FloatField(default=0)),
                ('commission_shop_manager', models.FloatField(default=0)),
                ('commission_minus', models.FloatField(default=0)),
                ('other_salary', models.FloatField(default=0)),
                ('total_salary', models.FloatField(default=0)),
                ('calculate_finished', models.BooleanField(default=False)),
                ('whose_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('commission_rate', models.CharField(default=0, max_length=10)),
                ('type', models.IntegerField(choices=[(1, '单租，定制'), (2, '升级为升级金额'), (3, '大牌套系租赁'), (4, '璀璨套系租赁')])),
                ('order_time', models.DateField()),
                ('wedding_time', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
                ('is_task_order', models.BooleanField(default=False)),
                ('is_discount_order', models.BooleanField(default=False)),
                ('is_chargeback', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, '已付定金'), (2, '已付尾款'), (3, '已完成'), (4, '已退款')])),
                ('order_number', models.IntegerField(unique=True)),
                ('whose_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage.Employee')),
            ],
        ),
    ]
