# Generated by Django 2.1.5 on 2019-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manual_add',
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate_new',
            field=models.FloatField(default=0, verbose_name='新订单提成'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate_wed',
            field=models.FloatField(default=0, verbose_name='完成服务提成'),
        ),
        migrations.AddField(
            model_name='order',
            name='unusual_change',
            field=models.TextField(null=True, verbose_name='异常状态'),
        ),
    ]
