# Generated by Django 2.1.5 on 2019-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='键')),
                ('val', models.TextField(verbose_name='值')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_chargeback',
        ),
    ]
