# Generated by Django 2.1.5 on 2019-01-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已付定金'), (1, '已付尾款'), (2, '已完成'), (3, '已退款')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, '单租，定制'), (1, '升级为升级金额'), (2, '大牌套系租赁'), (3, '璀璨套系租赁')]),
        ),
    ]
