# Generated by Django 2.1.5 on 2019-03-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0002_auto_20190313_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_and_changepeople',
            field=models.BooleanField(default=False, verbose_name='更换人且为任务单（勿手动修改）'),
        ),
    ]
