# Generated by Django 2.1.5 on 2019-02-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0002_auto_20190220_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '配置', 'verbose_name_plural': '配置'},
        ),
    ]
