# Generated by Django 2.1.5 on 2019-01-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0002_auto_20190129_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission_rate',
            field=models.FloatField(default=0),
        ),
    ]
