# Generated by Django 2.1.5 on 2019-03-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0003_order_task_and_changepeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_discount_order',
        ),
    ]
