# Generated by Django 2.1.5 on 2019-01-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0003_auto_20190129_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='calculate_finished',
            field=models.BooleanField(default=False),
        ),
    ]
