# Generated by Django 2.1.5 on 2019-02-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0004_auto_20190221_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '不处理'), (1, '已付定金'), (2, '已付尾款'), (3, '已完成'), (4, '已退款'), (5, '待退款')], verbose_name='订单状态'),
        ),
    ]
