# Generated by Django 2.1.5 on 2019-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0005_auto_20190315_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymoney',
            name='total_salary_remark',
            field=models.TextField(default='', verbose_name='额外调整明细'),
        ),
    ]
