# Generated by Django 2.1.5 on 2019-01-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0005_auto_20190129_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymoney',
            name='calculate_finished',
        ),
    ]
