# Generated by Django 2.1.5 on 2019-01-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0006_remove_monthlymoney_calculate_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calculated',
            field=models.BooleanField(default=False, verbose_name='已被计入'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_pay',
            field=models.FloatField(verbose_name='底薪'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='calculate_finished',
            field=models.BooleanField(default=False, verbose_name='计算完毕'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='commission_rate',
            field=models.CharField(max_length=100, verbose_name='提点'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='店员'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='on_job',
            field=models.BooleanField(default=True, verbose_name='在职'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shop_manager',
            field=models.BooleanField(default=False, verbose_name='店长'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='superior_income_rate',
            field=models.FloatField(verbose_name='徒弟提点'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='task_quantity',
            field=models.IntegerField(verbose_name='任务单量'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='wage.Employee', verbose_name='师父'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='base_salary',
            field=models.FloatField(default=0, verbose_name='底薪'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='commission_before',
            field=models.FloatField(default=0, verbose_name='以往留存提成'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='commission_current',
            field=models.FloatField(default=0, verbose_name='当月订单提成'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='commission_minus',
            field=models.FloatField(default=0, verbose_name='罚款'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='commission_passive',
            field=models.FloatField(default=0, verbose_name='带徒弟提成'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='commission_shop_manager',
            field=models.FloatField(default=0, verbose_name='店长提成'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='month',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='other_salary',
            field=models.FloatField(default=0, verbose_name='额外调整'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='total_salary',
            field=models.FloatField(default=0, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='whose_salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage.Employee', verbose_name='店员'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission_rate',
            field=models.FloatField(default=0, verbose_name='提成'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_chargeback',
            field=models.BooleanField(default=False, verbose_name='退单'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_discount_order',
            field=models.BooleanField(default=False, verbose_name='活动单'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_task_order',
            field=models.BooleanField(default=False, verbose_name='任务单'),
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateField(verbose_name='预定时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已付定金'), (1, '已付尾款'), (2, '已完成'), (3, '已退款')], verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, '单租，定制'), (1, '升级为升级金额'), (2, '大牌套系租赁'), (3, '璀璨套系租赁')], verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wedding_time',
            field=models.DateField(verbose_name='婚礼时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='whose_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage.Employee', verbose_name='店员'),
        ),
    ]
