# Generated by Django 2.1.5 on 2019-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0006_auto_20190221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymoney',
            name='details_back',
            field=models.TextField(blank=True, null=True, verbose_name='退单明细'),
        ),
        migrations.AddField(
            model_name='monthlymoney',
            name='details_manager',
            field=models.TextField(blank=True, null=True, verbose_name='全店明细'),
        ),
        migrations.AddField(
            model_name='monthlymoney',
            name='details_new',
            field=models.TextField(blank=True, null=True, verbose_name='新增订单明细'),
        ),
        migrations.AddField(
            model_name='monthlymoney',
            name='details_task',
            field=models.TextField(blank=True, null=True, verbose_name='任务单明细'),
        ),
        migrations.AddField(
            model_name='monthlymoney',
            name='details_teacher',
            field=models.TextField(blank=True, null=True, verbose_name='师父明细'),
        ),
        migrations.AddField(
            model_name='monthlymoney',
            name='details_wed',
            field=models.TextField(blank=True, null=True, verbose_name='结婚订单明细'),
        ),
    ]
