# Generated by Django 2.1.5 on 2019-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0006_monthlymoney_total_salary_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlymoney',
            old_name='total_salary_remark',
            new_name='other_salary_remark',
        ),
    ]
