# Generated by Django 2.1.5 on 2019-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0007_auto_20190307_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymoney',
            name='details_back',
            field=models.TextField(default='', verbose_name='退单明细'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='details_manager',
            field=models.TextField(default='', verbose_name='全店明细'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='details_new',
            field=models.TextField(default='', verbose_name='新增订单明细'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='details_task',
            field=models.TextField(default='', verbose_name='任务单明细'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='details_teacher',
            field=models.TextField(default='', verbose_name='师父明细'),
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='details_wed',
            field=models.TextField(default='', verbose_name='结婚订单明细'),
        ),
    ]
