# Generated by Django 2.1.5 on 2019-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0007_auto_20190130_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
        migrations.AlterModelOptions(
            name='monthlymoney',
            options={'verbose_name': '月薪', 'verbose_name_plural': '月薪'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='monthlymoney',
            name='commission_minus',
            field=models.FloatField(default=0, verbose_name='退单'),
        ),
        migrations.AlterField(
            model_name='order',
            name='calculated',
            field=models.BooleanField(default=False, verbose_name='已被计入当月提成'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '不处理'), (1, '已付定金'), (2, '已付尾款'), (3, '已完成'), (4, '已退款')], verbose_name='订单状态'),
        ),
    ]
