# Generated by Django 2.1.5 on 2019-01-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0009_monthlymoney_remaining_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymoney',
            name='remaining_task',
        ),
        migrations.AddField(
            model_name='monthlymoney',
            name='task_finished',
            field=models.IntegerField(default=0, verbose_name='已完成任务单'),
        ),
    ]
