# Generated by Django 2.1.5 on 2019-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0010_auto_20190130_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='订单号'),
        ),
    ]
