# Generated by Django 2.1.5 on 2019-02-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0011_auto_20190131_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_date',
            field=models.DateField(blank=True, null=True, verbose_name='状态改变时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_status',
            field=models.IntegerField(choices=[(0, '不处理'), (1, '已付定金'), (2, '已付尾款'), (3, '已完成'), (4, '已退款')], default=1, verbose_name='订单原始状态'),
            preserve_default=False,
        ),
    ]
